export default [
  {
    id: 1,
    title: 'coffee and croissant',
    category: 'breakfast',
    price: 15.99,
    img: 'https://i.imgur.com/WEYgmxm.jpg',
    desc: `croissant chocolate. Cake sugar plum fruitcake muffin gummi bears fruitcake tart cake. Dragée chocolate biscuit dessert donut powder tootsie roll danish tootsie roll.`,
  },
  {
    id: 2,
    title: 'pizza',
    category: 'lunch',
    price: 13.99,
    img: 'https://i.imgur.com/L8NkLhN.jpg',
    desc: `Chuck ham hock pig leberkas drumstick picanha shankle short loin flank chicken buffalo bacon ground round fatback frankfurter.`,
  },
  {
    id: 3,
    title: 'orange-cake',
    category: 'desserts',
    price: 6.99,
    img: 'https://i.imgur.com/x3zTSYI.jpg',
    desc: `Tiramisu cupcake oat cake jelly-o oat cake chocolate cake. Tart pastry carrot cake cookie muffin. Pudding brownie  fruitcake sugar plum apple pie bonbon.`,
  },
  {
    id: 4,
    title: 'pasta',
    category: 'lunch',
    price: 20.99,
    img: 'https://i.imgur.com/X0nYAoo.jpg',
    desc: `Meatball pancetta boudin ribeye, sausage landjaeger spare ribs filet mignon sirloin. `,
  },
  {
    id: 5,
    title: 'eclair',
    category: 'desserts',
    price: 22.99,
    img: 'https://i.imgur.com/5RZy29Q.jpg',
    desc: `Chocolate bar sugar plum fruitcake chupa chups topping. Macaroon topping cupcake gummi bears chocolate bar brownie macaroon soufflé.  `,
  },
  {
    id: 6,
    title: 'fried-eggs',
    category: 'breakfast',
    price: 18.99,
    img: 'https://i.imgur.com/RXjnu7U.jpg',
    desc: `Carrot grape soko wakame plantain pea broccoli rabe desert raisin. Chard cabbage cress gumbo spinach mung `,
  },
  {
    id: 7,
    title: 'lemon-tart',
    category: 'desserts',
    price: 8.99,
    img: 'https://i.imgur.com/iVtut2n.jpg',
    desc: `Soufflé powder topping pastry wafer cookie halvah. Topping macaroon pie pie candy canes caramels croissant chocolate. Cake sugar plum fruitcake muffin.  `,
  },
  {
    id: 8,
    title: 'fruit-muesli',
    category: 'breakfast',
    price: 12.99,
    img: 'https://i.imgur.com/XKm8AJO.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'soup',
    category: 'lunch',
    price: 16.99,
    img: 'https://i.imgur.com/OveOvP2.jpg',
    desc: `bean turnip greens rock melon chicory collard greens bok choy. Wattle seed wakame eggplant soybean quandong garlic prairie turnip swiss chard radish okra.`,
  },
];